import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head"; // Import Head for adding favicon

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RishiVerse",
  description: "Generated by create next app",
  icons: {
    icon: "https://static.vecteezy.com/system/resources/previews/029/271/191/non_2x/hipster-face-with-beard-and-mustache-logo-template-vector.jpg",
  },
};

const roboto = Geist({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotoMono = Geist_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
